---
- name: Create application folder
  file:
    name: "/opt/status/src"
    state: directory
- name: Retrieve application source files
  git:
    clone: yes
    force: yes
    dest: "/tmp/status"
    repo: "http://github.com/jimrigsbee/api.git"
- name: Copy application files
  copy:
    dest: "/opt/status/src/{{ item }}"
    src: "/tmp/status/{{ item }}"
    owner: "{{ ansible_user }}"
    mode: 0644
    remote_src: true
  with_items:
    - requirements.txt
    - server.py
    - wsgi.py
- name: Install python virtualenv
  pip:
    name: virtualenv

- name: Allow nginx to access non-standard port
  shell: |
    semanage port -a -t http_port_t -p tcp 30904
    semanage port -m -t http_port_t -p tcp 30904
    
- name: Install python application as a service
  include_role:
    name: Stouts.wsgi
  vars:
    python_enabled: false
    wsgi_group: nginx
    wsgi_nginx_servernames: "bastion.{{ guid }}{{ subdomain_base_suffix }}"
    wsgi_nginx_port: 30904
    wsgi_applications:
    - name: status
      server: gunicorn
      module: wsgi
      pip_requirements: requirements.txt
- name: Create runtime folders
  file:
    name: "{{item}}"
    state: directory
    owner: "{{ansible_user}}"
    group: nginx
  with_items:
    - /opt/status/run
    - /opt/status/log
- name: Fix selinux context for nginx access
  shell: |
    semanage fcontext -a -t httpd_sys_rw_content_t "{{item}}(/.*)?"
    restorecon -R -v "{{item}}"
  with_items:
    - /opt/status/run
    - /opt/status/log
# - name: Activate application service
#   service:
#     name: status-wsgi
#     state: started
#     enabled: yes
