---

- name: Install required packages
  yum:
    name: "{{ idm_rpms }}"
    state: installed
    use_backend: dnf

- name: Upgrade NSS package
  yum:
    name: nss
    state: latest
    use_backend: dnf

# Cannot use a handler here
- name: Ensure firewalld is running
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Open Firewall for IdM use
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
  - ntp
  - http
  - https
  - ldap
  - ldaps
  - kerberos
  - kpasswd
