---
- name: Install packages
  yum:
    name:
      - NetworkManager
    state: present
    use_backend: dnf

- name: Set hostname
  hostname:
    name: "{{ hostvars[inventory_hostname].instance_name}}.{{ dns_domain_name }}"

- name: Create dhclient.conf
  file:
    path: /etc/dhcp/dhclient.conf
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Discover domain controller host
  set_fact:
    dc_host: "{{groups['activedirectories'][0]}}"

- name: Set custom DNS server
  blockinfile:
    dest: /etc/dhcp/dhclient.conf
    block: |
      prepend domain-name-servers {{ hostvars[dc_host].private_ip_address }};
      prepend domain-search "{{ dns_domain_name }}", "ec2.internal";
    state: present
  register: dnschange

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
  when: dnschange.changed
