---
- name: Install packages
  package:
    name:
      - NetworkManager
    state: present

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}.{{ dns_domain_name }}"

- name: Create dhclient.conf
  file:
    path: /etc/dhcp/dhclient.conf
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Set custom DNS server
  blockinfile:
    dest: /etc/dhcp/dhclient.conf
    block: |
      prepend domain-name-servers {{ hostvars['windc'].private_ip_address }};
      prepend domain-search "{{ dns_domain_name }}", "ec2.internal";
    state: present
  register: dnschange

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
  when: dnschange.changed
