---

- name: GitLab Post | Obtain Access Token
  uri:
    url: https://gitlab.{{ dns_domain_name }}/oauth/token
    method: POST
    validate_certs: no
    status_code: 200
    body_format: json
    headers:
      Content-Type: application/json
    body: >
      {
        "grant_type": "password",
        "username": "root",
        "password": "{{ windows_password }}"
      }
  register: gitlab_access_token

- name: GitLab Post | Create local users via API
  uri:
    url: https://gitlab.{{ dns_domain_name }}/api/v4/users
    method: POST
    validate_certs: no
    status_code:
      - 200
      - 201
      - 409
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ gitlab_access_token.json.access_token }}
    body: >
      {
        "username": "{{ user_prefix }}",
        "password": "{{ windows_password }}",
        "name": "{{ user_prefix }}",
        "email": "{{ user_prefix }}@{{ dns_domain_name }}",
        "skip_confirmation": true
      }

# - name: GitLab Post | Get local user information via API
#   uri:
#     url: https://gitlab.{{ dns_domain_name }}/api/v4/users?username={{ user_prefix }}
#     method: GET
#     validate_certs: no
#     status_code:
#       - 200
#       - 201
#     headers:
#       Content-Type: application/json
#       Authorization: Bearer {{ gitlab_access_token.json.access_token }}
#   register: gitlab_local_users
#
# - name: debug
#   debug:
#     var: gitlab_local_users
#
# - name: GitLab Post | Create Projects via API
#   uri:
#     url: https://gitlab.{{ dns_domain_name }}/api/v4/projects/user/{{ item.id }}
#     method: POST
#     validate_certs: no
#     status_code:
#       - 200
#       - 201
#       - 409
#       - 400
#     body_format: json
#     headers:
#       Content-Type: application/json
#       Authorization: Bearer {{ gitlab_access_token.json.access_token }}
#     body: >
#       {
#         "name": "{{ item.name }}",
#         "group": "{{ item.name }}",
#         "issues_enabled": false,
#         "wiki_enabled": false,
#         "snippets_enabled": false
#       }
#   with_items:
#     - "{{ gitlab_local_users.json }}"
#   when: item.id is defined
