- name: Step 00xxxxx post software
  hosts: support
  gather_facts: False
  become: yes
  tasks:
    - debug:
        msg: "Post-Software tasks Started"

- name: Cleanup Windows Proxying
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Stop SSH/Socks proxy for Windows proxying through bastion
      shell: |
        ssh -i {{ ssh_key | default(infra_ssh_key) | default(ansible_ssh_private_key_file) | default(default_key_name)}} -o "ControlPath=~/.ssh/cp/ssh-%r@%h:%p" -O stop -p 22 {{hostvars[bastion_hostname].ansible_user}}@{{hostvars[bastion_hostname].public_dns_name}}
      when: win_connect_method | d('winrm') == 'psrp'

- name: Copy files to workstation
  hosts: workstations
  tasks:
    - name: Copy Ansible Inventory for this environment
      win_copy:
        src: "{{output_dir}}/hosts-{{ env_type }}-{{ guid }}"
        dest: "C:\\inventory.ini"

- name: PostSoftware flight-check
  hosts: towers
  gather_facts: false
  become: true
  tags:
    - post_flight_check
  tasks:
    - name: Get rid of conflicting SSL library
      package:
        name: pyOpenSSL
        state: absent

    - name: Upgrade requests-credssp module
      pip:
        name: requests-credssp
        state: latest

    - name: Test Ansible connectivity to Windows servers
      shell: |
        ansible windows -m win_ping
      register: ansible_check
      ignore_errors: true

    - debug:
        msg: "[ERROR] Ansible connectivity from Tower failed"
      when: ansible_check is failed

    - debug:
        msg: "Post-Software checks completed successfully"
