---
- name: Step 00xxxxx software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

- name: Step 001 software: Configure Active Directory DC
  hosts: activedirectories
  gather_facts: true
  tags:
    - windows-ad-controller
  roles:
    - skylight-windows-ad

- name: Step 002 software: Configure Windows Servers
  hosts: windows
  gather_facts: true
  tags:
    - windows-servers
  roles:
    - skylight-windows-common

- name: Step 003.1 software: Configure GitLab Host
  hosts: gitlab
  become: true
  gather_facts: true
  tags:
    - gitlab
  roles:
    - skylight-linux-common
    - geerlingguy.gitlab

- name: Step 003.2 software: Configure Gitlab Environment
  hosts: gitlab
  become: true
  gather_facts: true
  tags:
    - gitlab
  roles:
    - skylight-gitlab-env

# Should this be in post software????  A workload???
# TODO: figure out how to get to source code
# - name: Step 003.3 software: Configure DO417
#   import_playbook: do417-populate-repos.yml
#   when: install_courseware

- name: Step 004 software: Configure Ansible Tower
  hosts: towers
  become: true
  gather_facts: true
  tags:
    - ansible-tower
  roles:
    - skylight-linux-common
    - skylight-ansible-tower

- name: Step 005 software: Configure Windows Workstation
  hosts: workstations
  gather_facts: true
  tags:
    - windows-workstation
  roles:
    - skylight-windows-workstation

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
