---
- name: Step 00xxxxx software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

- name: Report Provisioning Status
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  tasks:
    - name: Report provisioning status
      include_role:
        name: status-report
      vars:
        classroom_status: "Servers provisioned 1 of 6"
        status_json: "{{ lookup('template', 'report.j2') }}"
      when: report_status

- name: Step 001 software - Configure Active Directory DC
  hosts: activedirectories
  gather_facts: true
  tags:
    - windows-ad-controller
  roles:
    - skylight-windows-ad

- name: Report Provisioning Status
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  tasks:
    - name: Report provisioning status
      include_role:
        name: status-report
      vars:
        classroom_status: "Active Directory configured 2 of 6"
        status_json: "{{ lookup('template', 'report.j2') }}"
      when: report_status

- name: Step 002 software - Configure Windows Servers
  hosts:
    - windows_servers
    - workstations
  gather_facts: true
  tags:
    - windows-servers
  roles:
    - skylight-windows-common

- name: Report Provisioning Status
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  tasks:
    - name: Report provisioning status
      include_role:
        name: status-report
      vars:
        classroom_status: "Windows servers configured 3 of 6"
        status_json: "{{ lookup('template', 'report.j2') }}"
      when: report_status

- name: Step 003.1 software - Configure GitLab Host
  hosts: gitlab
  become: true
  gather_facts: true
  tags:
    - gitlab
  roles:
    - skylight-linux-common
    - geerlingguy.gitlab

- name: Step 003.2 software - Configure Gitlab Environment
  hosts: gitlab
  become: true
  gather_facts: true
  tags:
    - gitlab
  roles:
    - skylight-gitlab-env

- name: Step 003.3 software - Configure DO417 repos
  hosts: gitlab
  become: False
  gather_facts: False
  tags:
    - gitlab
  roles:
    - skylight-do417-repos

- name: Report Provisioning Status
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  tasks:
    - name: Report provisioning status
      include_role:
        name: status-report
      vars:
        classroom_status: "Gitlab configured 4 of 6"
        status_json: "{{ lookup('template', 'report.j2') }}"
      when: report_status

- name: Step 004 software - Configure Ansible Tower
  hosts: towers
  become: true
  gather_facts: true
  tags:
    - ansible-tower
  roles:
    - skylight-linux-common
    - skylight-ansible-tower

- name: Report Provisioning Status
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  tasks:
    - name: Report provisioning status
      include_role:
        name: status-report
      vars:
        classroom_status: "Ansible Tower configured 5 of 6"
        status_json: "{{ lookup('template', 'report.j2') }}"
      when: report_status

- name: Step 005 software - Configure Windows Workstation
  hosts: workstations
  gather_facts: true
  tags:
    - windows-workstation
  roles:
    - skylight-windows-workstation

- name: Report Provisioning Status
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  tasks:
    - name: Report provisioning status
      include_role:
        name: status-report
      vars:
        classroom_status: "Windows Workstation configured 6 of 6"
        status_json: "{{ lookup('template', 'report.j2') }}"
      when: report_status

- name: Step 00xxxxx software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks Ended"
