---
- name: Install workloads
  hosts: bastions
  gather_facts: false
  run_once: true
  become: false

  tasks:
    - name: Include private workloads
      include_role:
        name: "{{ item.tmp }}"
      vars:
        ACTION:                  "provision"
        workload_name:           "{{ item.name }}"
        workload_git_url:        "{{ item.url }}"
        workload_git_path:       "{{ item.path }}"
        workload_ssh_key:        "{{ item.ssh_key }}"
      loop: "{{ private_workloads }}"