---
- name: Install workloads
  hosts: bastions
  gather_facts: false
  run_once: true
  become: false

  tasks:
    - name: Include private workloads
      include_role:
        name: "{{ item }}"
      vars:
        ACTION: "provision"
     loop: "{{ private_workloads }}"